AWSTemplateFormatVersion: "2010-09-09"
Description: TodoApp ECS Cluster, Fargate Service with ALB and Auto Scaling

Parameters:
  AppName:
    Type: String
  ECRImageUri:
    Type: String
  VPCId:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  S3BucketName:
    Description: "Name of the S3 bucket for images"
    Type: String
  VPCEndpointSG:
    Description: "Security Group for VPC endpoints"
    Type: AWS::EC2::SecurityGroup::Id
  ECSSecurityGroup:
    Description: "Security Group for ECS task"
    Type: AWS::EC2::SecurityGroup::Id
  ALBSecurityGroup:
    Description: "Security Group for Application Load Balancer"
    Type: AWS::EC2::SecurityGroup::Id
  LabTag:
    Type: String
  PORT:
    Description: "Port on which the backend application runs"
    Type: String
    Default: "8080"

Resources:
  # TodoApp ECS Autoscaling Role
  TodoAppECSAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole
      Policies:
        - PolicyName: !Sub ${AppName}-ecs-autoscaling-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "application-autoscaling:*"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:PutMetricAlarm"
                  - "ecs:DescribeServices"
                  - "ecs:UpdateService"
                  - "logs:PutLogEvents"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-ecs-autoscaling-role
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp ECS Task Execution Role
  TodoAppTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-ecs-task-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AppName}-ECRAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:DescribeImages
                Resource: "*"
        - PolicyName: !Sub ${AppName}-SSMAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:GetParametersByPath
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/wk-7-todo-app/*"
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*"
        - PolicyName: !Sub ${AppName}-S3AccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:CreateBucket
                Resource: "*"
        - PolicyName: !Sub ${AppName}-LoggingAccess
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - logs:DescribeLogStreams
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-task-execution-role
        - Key: Lab
          Value: !Ref LabTag


  # TodoApp DynamoDB ECS Task Role
  TodoAppTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-ecs-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AppName}-DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TodoItems
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TodoItems/index/*
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-task-role
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp Elastic Container Service (ECS) Cluster
  TodoAppECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AppName}-ecs-cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-ecs-cluster
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp ECS Service
  TodoAppECSService:
    Type: AWS::ECS::Service
    DependsOn: TodoAppListener
    Properties:
      ServiceName: !Sub ${AppName}-ecs-service
      Cluster: !Ref TodoAppECSCluster
      LaunchType: FARGATE
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 120
      DeploymentController:
        Type: CODE_DEPLOY
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
          SecurityGroups: 
            - !Ref ECSSecurityGroup
            - !Ref VPCEndpointSG
      LoadBalancers:
        - ContainerName: !Sub ${AppName}-container
          ContainerPort: 8081
          TargetGroupArn: !Ref TodoAppTargetGroup
      TaskDefinition: !Ref TodoAppTaskDefinition
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-ecs-service
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp ECS Task Definition
  TodoAppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppName}-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: 
        - FARGATE
      ExecutionRoleArn: !GetAtt TodoAppTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TodoAppTaskRole.Arn
      ContainerDefinitions:
        - Name: !Sub ${AppName}-container
          Image: !Ref ECRImageUri
          Essential: true
          PortMappings:
            - ContainerPort: 8081
              Protocol: tcp
          Environment:
            - Name: AWS_REGION
              Value: !Ref "AWS::Region"
            - Name: S3_BUCKET_NAME
              Value: !Ref S3BucketName
            - Name: PORT
              Value: !Ref PORT
            - Name: GIN_MODE
              Value: release
         
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TodoAppCloudWatchLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
              awslogs-create-group: "true"
          HealthCheck:
            Command:
              - "CMD-SHELL"
              - "/bin/sh -c 'curl -f http://localhost:8081 || exit 1'"
            Interval: 30
            Timeout: 10
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-task-definition
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp Application Load Balancer
  TodoAppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${AppName}-alb
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      Subnets: [!Ref PublicSubnet1, !Ref PublicSubnet2]
      SecurityGroups: [!Ref ALBSecurityGroup]
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-alb
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp Load Balancer Target Group
  TodoAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AppName}-blue-tg
      Port: 8081
      Protocol: HTTP
      VpcId: !Ref VPCId
      TargetType: ip
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-299
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-btg
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp Blue/Green CodeDeploy Target Group
  TodoAppTargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AppName}-green-tg
      Port: 8081
      Protocol: HTTP
      VpcId: !Ref VPCId
      TargetType: ip
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-299
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-gtg
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp Load Balancer Listener
  TodoAppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TodoAppTargetGroup
      LoadBalancerArn: !Ref TodoAppLoadBalancer
      Port: 80
      Protocol: HTTP

  # TodoApp CloudWatch Log Group
  TodoAppCloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AppName}
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-ecs-logs
        - Key: Lab
          Value: !Ref LabTag

  # TodoApp Target Auto Scaling
  TodoAppAutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn:
      - TodoAppECSService
    Properties:
      MaxCapacity: 4
      MinCapacity: 2
      ResourceId: !Sub service/${AppName}-ecs-cluster/${AppName}-ecs-service
      RoleARN: !GetAtt TodoAppECSAutoScalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # TodoApp Auto Scaling Policy
  TodoAppAutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${AppName}-cpu-scaling-policy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref TodoAppAutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

Outputs:
  AppLoadBalancerDNS:
    Description: TodoApp ALB DNS to access app
    Value: !GetAtt TodoAppLoadBalancer.DNSName

  ClusterName:
    Description: Name of the TodoApp ECS Cluster
    Value: !Ref TodoAppECSCluster
    Export:
      Name: !Sub ${AppName}-ecs-cluster

  ServiceName:
    Description: TodoApp ECS Service Name
    Value: !Sub ${AppName}-ecs-service
    Export:
      Name: !Sub ${AppName}-ecs-service

  BlueTargetGroupName:
    Description: Name of the first TodoApp target group
    Value: !GetAtt TodoAppTargetGroup.TargetGroupName
    Export:
      Name: BlueTargetGroupName

  GreenTargetGroupName:
    Description: Name of the second TodoApp target group
    Value: !GetAtt TodoAppTargetGroup2.TargetGroupName
    Export:
      Name: GreenTargetGroupName

  ALBListenerArn:
    Description: ARN of the TodoApp Load Balancer Listener
    Value: !Ref TodoAppListener
    Export:
      Name: ALBListenerArn

  TaskExecRoleArn:
    Description: ARN of the TodoApp TaskExecutionRole
    Value: !Ref TodoAppTaskExecutionRole
    Export:
      Name: TaskExecRoleArn