AWSTemplateFormatVersion: "2010-09-09"
Description: Root Stack for ECS Go and Angular TodoApp App with DynamoDB, Auto Scaling, ALB, and CodePipeline

Parameters:
  AppName:
    Type: String
    Default: todo-app
  LabTag:
    Type: String
    Default: week7_lab
  TemplateS3BaseURL:
    Description: "S3 Base URL where templates are stored"
    Type: String
    Default: https://wk-7-todo-app-bucket.s3.eu-west-1.amazonaws.com/infra
  ECRImageUri:
    Type: String
    Default: 124355655853.dkr.ecr.eu-west-1.amazonaws.com/todo-app-repo:latest

Resources:
  # TodoApp VPC Stack
  TodoAppVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/vpc.yaml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag

  # TodoApp Security Groups Stack
  TodoAppSecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/security-groups.yaml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag
        VPCId: !GetAtt TodoAppVPCStack.Outputs.VPCId

  # TodoApp ECS Application Stack
  TodoAppECSAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/alb.yaml"
      Parameters:
        VPCId: !GetAtt TodoAppVPCStack.Outputs.VPCId
        PublicSubnet1: !GetAtt TodoAppVPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2: !GetAtt TodoAppVPCStack.Outputs.PublicSubnet2Id
        PrivateSubnet1: !GetAtt TodoAppVPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2: !GetAtt TodoAppVPCStack.Outputs.PrivateSubnet2Id
        VPCEndpointSG: !GetAtt TodoAppVPCStack.Outputs.VPCEndpointSG
        ECSSecurityGroup: !GetAtt TodoAppSecurityGroupsStack.Outputs.ECSSecurityGroup
        ALBSecurityGroup: !GetAtt TodoAppSecurityGroupsStack.Outputs.ALBSecurityGroup
        AppName: !Ref AppName
        LabTag: !Ref LabTag
        ECRImageUri: !Ref ECRImageUri

  # TodoApp CodeDeploy Stack
  TodoAppCodeDeployStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/code-deploy.yaml"
      Parameters:
        ClusterName: !GetAtt TodoAppECSAppStack.Outputs.ClusterName
        ServiceName: !GetAtt TodoAppECSAppStack.Outputs.ServiceName
        TargetGroup1: !GetAtt TodoAppECSAppStack.Outputs.BlueTargetGroupName
        TargetGroup2: !GetAtt TodoAppECSAppStack.Outputs.GreenTargetGroupName
        ListenerArn: !GetAtt TodoAppECSAppStack.Outputs.ALBListenerArn
        AppName: !Ref AppName
        LabTag: !Ref LabTag

  # TodoApp CodePipeline Stack
  TodoAppCodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/code-pipeline.yaml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag
        CodeDeployApplication: !GetAtt TodoAppCodeDeployStack.Outputs.CodeDeployAppName
        CodeDeployDeploymentGroup: !GetAtt TodoAppCodeDeployStack.Outputs.CodeDeployDeploymentGroupName

Outputs:
  LoadBalancerDNS:
    Description: TodoApp ALB DNS to access app
    Value: !GetAtt TodoAppECSAppStack.Outputs.AppLoadBalancerDNS