name: Upload Infra Templates and CodeDeploy Files to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Upload Infrastructure Files
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.TEMPLATE_BUCKET_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint -t infra/*.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload infra/*.yaml to infra/ folder in S3
        run: |
          for file in infra/*.yaml; do
            aws s3 cp "$file" "s3://$S3_BUCKET/infra/$(basename $file)"
          done

      - name: Zip CodeDeploy files
        run: |
          cd pipeline
          zip ../codedeploy-bundle.zip appspec.yaml taskdef.json

      - name: Upload codedeploy-bundle.zip to S3
        run: |
          aws s3 cp codedeploy-bundle.zip s3://$S3_BUCKET/codedeploy-bundle.zip

      - name: Print uploaded Template URLs
        run: |
          for file in infra/*.yaml; do
            echo "https://$S3_BUCKET.s3.${AWS_REGION}.amazonaws.com/infra/$(basename $file)"
          done
